version: 1.0.0-{build}
configuration: Release
cache:
    - packages -> **\packages.config
before_build: nuget restore

build:
    publish_wap: true

test_script:
ps: vstest.console /logger:Appveyor "XP_BDD_1\bin\XP_BDD_1.dll" /TestAdapterPath:"packages"

deploy:
     provider: Environment
     name: XP_Specflow_Selenium_Test_Example
     on:
       branch: master
